/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-tint": "#106e00",
        "on-tertiary-fixed": "#0d1b34",
        "surface-bright": "#f9f9ff",
        "tertiary": "#515e7b",
        "surface-dim": "#d3daea",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dce2f3",
        "inverse-primary": "#7ddc64",
        "primary-fixed": "#98fa7d",
        "on-tertiary-container": "#2f3b56",
        "tertiary-container": "#99a6c6",
        "surface": "#f9f9ff",
        "on-primary": "#ffffff",
        "surface-variant": "#dce2f3",
        "secondary-fixed-dim": "#c1c8c2",
        "primary-container": "#5dba47",
        "outline-variant": "#bfcab6",
        "outline": "#707a69",
        "secondary-fixed": "#dde4dd",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "secondary": "#59605b",
        "surface-container": "#e7eefe",
        "primary": "#106e00",
        "background": "#f9f9ff",
        "surface-container-high": "#e2e8f8",
        "on-surface": "#151c27",
        "on-secondary-fixed-variant": "#414844",
        "secondary-container": "#dde4dd",
        "on-background": "#151c27",
        "tertiary-fixed-dim": "#b9c6e7",
        "inverse-on-surface": "#ebf1ff",
        "tertiary-fixed": "#d8e2ff",
        "surface-container-low": "#f0f3ff",
        "on-secondary-container": "#5f6661",
        "on-primary-fixed-variant": "#095300",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#3a4762",
        "on-surface-variant": "#404a3b",
        "on-primary-fixed": "#022100",
        "on-primary-container": "#074600",
        "on-secondary-fixed": "#161d19",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#7ddc64",
        "inverse-surface": "#2a313d",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "section-gap": "2rem",
        "stack-lg": "1.5rem",
        "stack-md": "1rem",
        "margin-page": "1.25rem",
        "stack-sm": "0.5rem",
        "gutter-grid": "1rem"
      },
      "fontFamily": {
        "headline-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "display": ["Manrope", "sans-serif"],
        "data-point": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-bold": ["Manrope", "sans-serif"]
      },
      "fontSize": {
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "display": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "data-point": ["18px", {"lineHeight": "22px", "fontWeight": "800"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "500"}],
        "label-bold": ["12px", {"lineHeight": "16px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
